services:
  - type: web
    name: anomaly-detection-api
    runtime: docker
    repo: https://github.com/Elvaceishim/anomaly-detection-system
    branch: main
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
